[package]
name = "deezer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.4", features = ["json", "cookies"] }
reqwest_cookie_store = "0.7.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tracing = "0.1.40"
url = "2.5.0"

[dev-dependencies]
tokio = { version = "1.35.1", features = ["net", "rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.18"
